name: Deploy Python Notebooks to PROD

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.PRO_DEVLOPEMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.PROD_DEVLOPMENT_TARGET_TOCKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Verify Databricks Connection
        run: |
          databricks current-user me

      - name: Show Repository Files
        run: |
          pwd
          ls -la
          ls -R

      - name: Create PROD folder (if it doesn't exist)
        run: |
          databricks workspace mkdirs "/Workspace/Users/mandrurajesh89@gmail.com/prod-actions/my-project"

      - name: Deploy to PROD
        run: |
          databricks workspace import-dir . "/Workspace/Users/mandrurajesh89@gmail.com/prod-actions/my-project" --overwrite
